CREATE TABLE reservation_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    seat_id BIGINT NOT NULL REFERENCES seats(id) ON DELETE RESTRICT,
    UNIQUE (seat_id, reservation_id)
);

CREATE INDEX idx_reservation_seats_reservation_id ON reservation_seats(reservation_id);
CREATE INDEX idx_reservation_seats_seat_id ON reservation_seats(seat_id);
