CREATE TABLE showtime_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    showtime_id BIGINT NOT NULL REFERENCES showtimes(id),
    seat_id BIGINT NOT NULL REFERENCES seats(id),

    reservation_id BIGINT REFERENCES reservations(id),

    status VARCHAR(15) NOT NULL,

    UNIQUE (showtime_id, seat_id)
);
