CREATE TABLE showtimes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  movie_id BIGINT NOT NULL REFERENCES movies(id),
  room_id BIGINT NOT NULL REFERENCES rooms(id),
  start_time TIMESTAMP NOT NULL
);
