spring.application.name=backend

spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
